### ISSUE TITLE
Weird Subject-Pellet-Delivery Visualizer Behavior

### ISSUE THREAD

**Issue by jkbhagatio** [SainsburyWellcomeCentre/aeon_experiments#555]
We've noticed that, when stopping a workflow, with an active subject, in maintenance mode, and relaunching the workflow, the pellet delivery visualizers stop working. @lorycalca

**Comment by jkbhagatio** [comment]
Can't always reliably reproduce however

**Comment by glopesdev** [comment]
@jkbhagatio which branch is this? Is it on main or in one of the issue branches?

**Comment by aspaNeuro** [comment]
I was online with Jai and we where unable to reproduce the same behavior. 
We were working on the RFID visualizer branch
We tried many times and agreed that it could be something else non related that happened on that specific time that the issue happened, so this issue is not major or blocking for the current experiment

**Comment by glopesdev** [comment]
Ok, I am clearing it from the milestone then, feel free to move it back if it happens again.

**Comment by jkbhagatio** [comment]
Couldn't recreate, so closing this, can re-open if we notice it again
